 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hilos;

import java.awt.FileDialog;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JPanel;
import java.io.File;
import javax.sound.sampled.*;
/**
 *
 * @author abel
 */
public class Creador extends javax.swing.JDialog {
static JPanel panel;
static ArrayList colonia;
String audio;
    /**
     * Creates new form Creador
     */
  

public Creador(java.awt.Frame parent, boolean modal,JPanel panel,ArrayList colonia) {
        super(parent, modal);
        initComponents();
        this.panel=panel;
        this.colonia=colonia;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        M = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        animal = new javax.swing.JRadioButton();
        vegetal = new javax.swing.JRadioButton();
        mineral = new javax.swing.JRadioButton();
        agua = new javax.swing.JRadioButton();
        Herbívoro = new javax.swing.JRadioButton();
        Carnívoro = new javax.swing.JRadioButton();
        Omnívoro = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        EDV = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EA = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LEF = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LD = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        velocidad = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        H = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        especie = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        clonar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Imagen Adulto");

        jLabel3.setText("Imagen  Cria");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Cargar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 4, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Cargar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Creador");

        jLabel20.setText("jLabel20");

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Cargar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(296, 400));

        jLabel10.setText("sexo");

        M.setBackground(new java.awt.Color(51, 51, 255));
        M.setText("Masculino");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });

        F.setBackground(new java.awt.Color(51, 51, 255));
        F.setText("Femenino");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });

        jLabel5.setText("Origen");

        animal.setBackground(new java.awt.Color(51, 51, 255));
        animal.setText("Animal");
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });

        vegetal.setBackground(new java.awt.Color(51, 51, 255));
        vegetal.setText("Vegetal");
        vegetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetalActionPerformed(evt);
            }
        });

        mineral.setBackground(new java.awt.Color(51, 51, 255));
        mineral.setText("Mineral");
        mineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineralActionPerformed(evt);
            }
        });

        agua.setBackground(new java.awt.Color(51, 51, 255));
        agua.setText("Agua");
        agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguaActionPerformed(evt);
            }
        });

        Herbívoro.setText("Herbívoro");
        Herbívoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HerbívoroActionPerformed(evt);
            }
        });

        Carnívoro.setText("Carnívoro");
        Carnívoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarnívoroActionPerformed(evt);
            }
        });

        Omnívoro.setText("Omnívoro");
        Omnívoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OmnívoroActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(7, 3));
        jPanel6.add(jLabel12);

        EDV.setMaximum(10000);
        EDV.setPaintLabels(true);
        EDV.setPaintTicks(true);
        EDV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EDVMouseDragged(evt);
            }
        });
        jPanel6.add(EDV);

        jLabel6.setText("Esperanza de Vida");
        jPanel6.add(jLabel6);
        jPanel6.add(jLabel13);

        EA.setMaximum(10000);
        EA.setPaintLabels(true);
        EA.setPaintTicks(true);
        EA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EAMouseDragged(evt);
            }
        });
        jPanel6.add(EA);

        jLabel7.setText("Edad Adulta");
        jPanel6.add(jLabel7);
        jPanel6.add(jLabel14);

        LEF.setMaximum(10000);
        LEF.setPaintLabels(true);
        LEF.setPaintTicks(true);
        LEF.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LEFMouseDragged(evt);
            }
        });
        jPanel6.add(LEF);

        jLabel8.setText("Limite Edad Fertil");
        jPanel6.add(jLabel8);
        jPanel6.add(jLabel15);

        LD.setPaintLabels(true);
        LD.setPaintTicks(true);
        LD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LDMouseDragged(evt);
            }
        });
        jPanel6.add(LD);

        jLabel9.setText("Limite de Descendientes");
        jPanel6.add(jLabel9);
        jPanel6.add(jLabel16);

        velocidad.setPaintLabels(true);
        velocidad.setPaintTicks(true);
        velocidad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                velocidadMouseDragged(evt);
            }
        });
        jPanel6.add(velocidad);

        jLabel2.setText("Velocidad de Traslacion");
        jPanel6.add(jLabel2);
        jPanel6.add(jLabel17);

        H.setMaximum(10000);
        H.setMinimum(1);
        H.setPaintLabels(true);
        H.setPaintTicks(true);
        H.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HMouseDragged(evt);
            }
        });
        jPanel6.add(H);

        jLabel11.setText("Frecuencia Hambre");
        jPanel6.add(jLabel11);
        jPanel6.add(jLabel18);
        jPanel6.add(especie);

        jLabel19.setText("Especie");
        jPanel6.add(jLabel19);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(animal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mineral, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Omnívoro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carnívoro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Herbívoro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M)
                    .addComponent(F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Herbívoro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Carnívoro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Omnívoro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mineral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agua)
                .addGap(183, 183, 183))
        );

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 30));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        crear.setBackground(new java.awt.Color(51, 51, 255));
        crear.setText("Crear");
        crear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 4, true));
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel5.add(crear);

        clonar.setBackground(new java.awt.Color(0, 0, 204));
        clonar.setText("Clonar");
        clonar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 4, true));
        clonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clonarActionPerformed(evt);
            }
        });
        jPanel5.add(clonar);

        guardar.setBackground(new java.awt.Color(51, 51, 255));
        guardar.setText("Guardar");
        guardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 4, true));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel5.add(guardar);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
     if ( vegetal.isSelected()) vegetal.setSelected(false);
     if ( mineral.isSelected()) mineral.setSelected(false);
     if ( agua.isSelected()) agua.setSelected(false);
      if (animal.isSelected()){ Herbívoro.setVisible(true);
                                Carnívoro.setVisible(true);
                                Omnívoro.setVisible(true);
      
                             }
      else{Herbívoro.setVisible(false);
                                Carnívoro.setVisible(false);
                                Omnívoro.setVisible(false);
      
       }

      // TODO add your handling code here:
    }//GEN-LAST:event_animalActionPerformed

    private void vegetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetalActionPerformed
      if ( animal.isSelected()) animal.setSelected(false);
     if ( mineral.isSelected()) mineral.setSelected(false);        
     if ( agua.isSelected()) agua.setSelected(false);
     
     if (animal.isSelected()){ Herbívoro.setVisible(true);
                                Carnívoro.setVisible(true);
                                Omnívoro.setVisible(true);
      
                             }
      else{Herbívoro.setVisible(false);
                                Carnívoro.setVisible(false);
                                Omnívoro.setVisible(false);
      
       }
// TODO add your handling code here:
    }//GEN-LAST:event_vegetalActionPerformed

    private void mineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineralActionPerformed
     if ( animal.isSelected()) animal.setSelected(false);
     if ( vegetal.isSelected()) vegetal.setSelected(false);
     if ( agua.isSelected()) agua.setSelected(false); 
     if (animal.isSelected()){ Herbívoro.setVisible(true);
                                Carnívoro.setVisible(true);
                                Omnívoro.setVisible(true);
      
                             }
      else{Herbívoro.setVisible(false);
                                Carnívoro.setVisible(false);
                                Omnívoro.setVisible(false);
      
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_mineralActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
       if ( F.isSelected()) F.setSelected(false);
             // TODO add your handling code here:
    }//GEN-LAST:event_MActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
    if ( M.isSelected()) M.setSelected(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_FActionPerformed
 
    
 String IMAGENCRIA=null,IMAGENADULTO=null;
 Ser nuevo=null;
 
 
    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
      int esperanzadevida,edadadulta,limiteedadreproductiva,limitededescendientes,vel,hambre;
        
      if (IMAGENCRIA==null)
              {
            javax.swing.JOptionPane.showMessageDialog(null,"Selecciona la imagen de la cria\n"
                                            + "del individuo que desea generar.","Error Lógico",javax.swing.JOptionPane.OK_OPTION);   
                               
                                return;  
                                 
                                }
      if (IMAGENADULTO==null)
              {
            javax.swing.JOptionPane.showMessageDialog(null,"Selecciona la imagen del \n"
                                            + "individuo adulto que desea generar.","Error Lógico",javax.swing.JOptionPane.OK_OPTION);   
                               
                                return;  
                                 
                                }
       if (audio==null)
              {
            javax.swing.JOptionPane.showMessageDialog(null,"Selecciona el sonido\n"
                                            + "del individuo que desea generar.","Error Lógico",javax.swing.JOptionPane.OK_OPTION);   
                               
                                return;  
                                 
                                }
      
      
    if (!vegetal.isSelected()&&!animal.isSelected()&&!mineral.isSelected()&&!agua.isSelected())
              {
            javax.swing.JOptionPane.showMessageDialog(null,"Selecciona el origen del \n"
                                            + "individuo que desea generar.","Error Lógico",javax.swing.JOptionPane.OK_OPTION);   
                               
                                return;  
                                 
                                }
         if (!M.isSelected()&&!F.isSelected())
             {
            javax.swing.JOptionPane.showMessageDialog(null,"Selecciona el sexo de la especie de \n"
                                            + "individuo que desea generar.","Error Lógico",javax.swing.JOptionPane.OK_OPTION);   
                               
                                return;  
                                 
                                }
             
              
          
        esperanzadevida=EDV.getValue();
        edadadulta=EA.getValue();
        limiteedadreproductiva=LEF.getValue();
        limitededescendientes=LD.getValue();
        vel=this.velocidad.getValue();
        hambre=this.H.getValue();
              
        
        try{
        if (edadadulta>esperanzadevida) throw new Exception("La esperanza de vida\n "
                + "no puede ser menor o igual\n"
                + "a la edad adulta");
        if (limiteedadreproductiva>esperanzadevida)throw new Exception("El limite de edad \n"
                + "de repreoduccion no puede ser\n"
                + "mayor que la esperanza de vida.");
        if (limiteedadreproductiva<edadadulta) throw new Exception("El limite de edad \n"
                + "de repreoduccion no puede ser\n"
                + "menor que la edad adulta.");
        
        }catch(Exception ex){ javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage(),"Error Lógico",javax.swing.JOptionPane.OK_OPTION);   
                               
                                return;  
        
           }      

         
         
        
        boolean sexo=(F.isSelected());
        String especie=this.especie.getText();
      
    if (animal.isSelected()) 
        {  if (Herbívoro.isSelected()) nuevo=new  Herbivoro(especie,audio,new javax.swing.ImageIcon(IMAGENCRIA),
                                               new javax.swing.ImageIcon(IMAGENADULTO),sexo,panel,colonia,
                                                  esperanzadevida,limiteedadreproductiva,edadadulta,limitededescendientes,vel,hambre);
            
           if (Carnívoro.isSelected()) nuevo=new  Carnivoro(especie,audio,new javax.swing.ImageIcon(IMAGENCRIA),
                                               new javax.swing.ImageIcon(IMAGENADULTO),sexo,panel,colonia,
                                                  esperanzadevida,limiteedadreproductiva,edadadulta,limitededescendientes,vel,hambre);
            
          if (Omnívoro.isSelected()) nuevo=new  Omnivoro(especie,audio,new javax.swing.ImageIcon(IMAGENCRIA),
                                               new javax.swing.ImageIcon(IMAGENADULTO),sexo,panel,colonia,
                                                  esperanzadevida,limiteedadreproductiva,edadadulta,limitededescendientes,vel,hambre);
              
                           
          }
      if (vegetal.isSelected())
          
      {   nuevo=new  Planta(especie,new javax.swing.ImageIcon(IMAGENCRIA),
              new javax.swing.ImageIcon(IMAGENADULTO),sexo,panel,colonia,
        esperanzadevida,limiteedadreproductiva,edadadulta,limitededescendientes,vel,hambre);
         
      }
      
      if(mineral.isSelected())
      {  nuevo=new  Piedra(especie,new javax.swing.ImageIcon(IMAGENCRIA),
              new javax.swing.ImageIcon(IMAGENADULTO),sexo,panel,colonia,
        esperanzadevida,limiteedadreproductiva,edadadulta,limitededescendientes,vel,hambre);
        
      }    
      
      if(agua.isSelected())
      {  nuevo=new  Agua(especie,audio,new javax.swing.ImageIcon(IMAGENCRIA),
              new javax.swing.ImageIcon(IMAGENADULTO),sexo,panel,colonia,
        esperanzadevida,limiteedadreproductiva,edadadulta,limitededescendientes,vel,hambre);
         
      }    
        
        panel.repaint();
        panel.validate();
// TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        FileDialog fd=new FileDialog(this,"",FileDialog.LOAD);
        fd.setVisible(true);
        IMAGENCRIA=fd.getDirectory()+fd.getFile();
        

        try{
        
        jLabel3.setText("");
        javax.swing.ImageIcon imagen=new javax.swing.ImageIcon(IMAGENCRIA);
        
        if (imagen.getIconWidth()>300||imagen.getIconHeight()>300) throw new Exception("Dimensiones incorrectas");
        else jLabel3.setIcon(imagen);
        
        }catch(Exception ex){              
            javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage(),"Error de Formato",javax.swing.JOptionPane.OK_OPTION);   
                                 IMAGENCRIA=null;
                                return;  
                                 
                                }
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           FileDialog fd=new FileDialog(this,"",FileDialog.LOAD);
        fd.setVisible(true);
        IMAGENADULTO=fd.getDirectory()+fd.getFile();
        
        try{
        
        jLabel4.setText("");
        javax.swing.ImageIcon imagen=new javax.swing.ImageIcon(IMAGENADULTO);
        
        if (imagen.getIconWidth()>300||imagen.getIconHeight()>300) throw new Exception("Dimensiones incorrectas");
        else jLabel4.setIcon(imagen);
        
        }catch(Exception ex){              
            javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage(),"Error de Formato",javax.swing.JOptionPane.OK_OPTION);   
                                 IMAGENADULTO=null;
                                return;  
                                 
                                }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguaActionPerformed
       if ( animal.isSelected()) animal.setSelected(false);
     if ( vegetal.isSelected()) vegetal.setSelected(false);
     if ( mineral.isSelected()) mineral.setSelected(false);  
    if (animal.isSelected()){ Herbívoro.setVisible(true);
                                Carnívoro.setVisible(true);
                                Omnívoro.setVisible(true);
      
                             }
      else{Herbívoro.setVisible(false);
                                Carnívoro.setVisible(false);
                                Omnívoro.setVisible(false);
      
       }
    
    
     // TODO add your handling code here:
    }//GEN-LAST:event_aguaActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
         try{
             crearActionPerformed(evt);
         FileDialog fd=new FileDialog(this,"",FileDialog.SAVE);
         fd.setVisible(true);
         String name=fd.getDirectory()+fd.getFile()+"."+nuevo.especie;
         ObjectOutputStream op=new ObjectOutputStream(new FileOutputStream(name));
         op.writeObject(nuevo);
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Ha sido imposible la grabacion","Error de ADN",javax.swing.JOptionPane.OK_OPTION); 
            
            
            e.printStackTrace();
        
        }



         // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void clonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clonarActionPerformed
    try{
        FileDialog fd=new FileDialog(this,"",FileDialog.LOAD);
        fd.setVisible(true);
        String name=fd.getDirectory()+fd.getFile();
        ObjectInputStream op=new ObjectInputStream(new FileInputStream(name));
        nuevo=(Ser)op.readObject();
        jLabel3.setText("");
        jLabel4.setText("");
        
        jLabel3.setIcon(nuevo.imagenCria);
        jLabel4.setIcon(nuevo.imagenAdulto);
        IMAGENADULTO=nuevo.imagenAdulto.toString();
        IMAGENCRIA=nuevo.imagenCria.toString();
        jLabel20.setText(nuevo.audio.toString());
        audio=nuevo.audio;
        if (nuevo instanceof Herbivoro) {animal.setSelected(true);
                                       mineral.setSelected(false);
                                       agua.setSelected(false);
                                       vegetal.setSelected(false);
                                       Carnívoro.setSelected(false);
                                       Omnívoro.setSelected(false);
                                       Herbívoro.setSelected(true);
        }
        if (nuevo instanceof Carnivoro) {animal.setSelected(true);
                                       mineral.setSelected(false);
                                       agua.setSelected(false);
                                       vegetal.setSelected(false);
                                       Herbívoro.setSelected(false);
                                       Omnívoro.setSelected(false);
                                       Carnívoro.setSelected(true);
        }
        if (nuevo instanceof Omnivoro) {animal.setSelected(true);
                                       mineral.setSelected(false);
                                       agua.setSelected(false);
                                       vegetal.setSelected(false);
                                       Carnívoro.setSelected(false);
                                       Herbívoro.setSelected(false);
                                       Omnívoro.setSelected(true);
        }
        if (nuevo instanceof Piedra) {animal.setSelected(false);
                                       mineral.setSelected(true);
                                       agua.setSelected(false);
                                       vegetal.setSelected(false);
        }
        if (nuevo instanceof Agua) {animal.setSelected(false);
                                       mineral.setSelected(false);
                                       agua.setSelected(true);
                                       vegetal.setSelected(false);
        }
        if (nuevo instanceof Planta) {animal.setSelected(false);
                                       mineral.setSelected(false);
                                       agua.setSelected(false);
                                       vegetal.setSelected(true);
        }
        
        EDV.setValue(nuevo.esperanzadevida);
        EA.setValue(nuevo.edadadulta);
        LEF.setValue(nuevo.limiteedadreproduccion);
        LD.setValue(nuevo.limitedescendientes);
        if(nuevo.esHembra()) {F.setSelected(true);M.setSelected(false);}
        else {M.setSelected(true);F.setSelected(false);}
        velocidad.setValue(nuevo.traslacion);
        H.setValue(nuevo.hambre);
        especie.setText(nuevo.especie);
         
         jLabel12.setText(EDV.getValue()+"");
         jLabel13.setText(EA.getValue()+"");
         jLabel14.setText(LEF.getValue()+"");
         jLabel15.setText(LD.getValue()+"");
         jLabel16.setText(velocidad.getValue()+"");
         jLabel17.setText(H.getValue()+"");
         
         crearActionPerformed(evt);
        panel.repaint();
        panel.validate();
         }catch(Exception ex){ 
        javax.swing.JOptionPane.showMessageDialog(null,
                    "Ha sido imposible la clonacion","Error de ADN",javax.swing.JOptionPane.OK_OPTION);               
        
         ex.printStackTrace();
         nuevo=null;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_clonarActionPerformed

    private void OmnívoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OmnívoroActionPerformed
   animal.setSelected(true);
        if (Carnívoro.isSelected()) Carnívoro.setSelected(false);
    if (Herbívoro.isSelected()) Herbívoro.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_OmnívoroActionPerformed

    private void HerbívoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HerbívoroActionPerformed
animal.setSelected(true);
   if (Carnívoro.isSelected()) Carnívoro.setSelected(false);
    if (Omnívoro.isSelected()) Omnívoro.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_HerbívoroActionPerformed

    private void CarnívoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnívoroActionPerformed
       animal.setSelected(true);
        if (Herbívoro.isSelected()) Herbívoro.setSelected(false);
    if (Omnívoro.isSelected()) Omnívoro.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_CarnívoroActionPerformed

    private void EDVMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDVMouseDragged
      jLabel12.setText(EDV.getValue()+"");

        // TODO add your handling code here:
    }//GEN-LAST:event_EDVMouseDragged

    private void EAMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EAMouseDragged

     jLabel13.setText(EA.getValue()+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_EAMouseDragged

    private void LEFMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LEFMouseDragged
    jLabel14.setText(LEF.getValue()+"");
 // TODO add your handling code here:
    }//GEN-LAST:event_LEFMouseDragged

    private void LDMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDMouseDragged
 jLabel15.setText(LD.getValue()+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_LDMouseDragged

    private void velocidadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_velocidadMouseDragged
 jLabel16.setText(velocidad.getValue()+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_velocidadMouseDragged

    private void HMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseDragged
 jLabel17.setText(H.getValue()+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_HMouseDragged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FileDialog fd=new FileDialog(this,"",FileDialog.LOAD);
        fd.setVisible(true);
        
        audio="/audios/"+fd.getFile();
        
        try{
                  
        jLabel20.setText(audio.toString());  
        
        }catch(Exception ex){              
            javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage(),"Error de Formato",javax.swing.JOptionPane.OK_OPTION);   
                                 audio=null;
                                return;  
                                 
                                }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Creador dialog = new Creador(new javax.swing.JFrame(), true, panel,colonia);
                    
                                       
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Carnívoro;
    public javax.swing.JSlider EA;
    public javax.swing.JSlider EDV;
    public javax.swing.JRadioButton F;
    public javax.swing.JSlider H;
    public javax.swing.JRadioButton Herbívoro;
    public javax.swing.JSlider LD;
    public javax.swing.JSlider LEF;
    public javax.swing.JRadioButton M;
    public javax.swing.JRadioButton Omnívoro;
    public javax.swing.JRadioButton agua;
    public javax.swing.JRadioButton animal;
    public javax.swing.JButton clonar;
    public javax.swing.JButton crear;
    public javax.swing.JTextField especie;
    public javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JRadioButton mineral;
    public javax.swing.JRadioButton vegetal;
    public javax.swing.JSlider velocidad;
    // End of variables declaration//GEN-END:variables
}
